# Generated by Django 4.2.2 on 2023-06-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sweet", "Sweet"),
                    ("hot", "Hot"),
                    ("snacks", "Snacks"),
                    ("pickles", "pickles"),
                ],
                max_length=10,
            ),
        ),
    ]
