# Generated by Django 4.2.2 on 2023-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sweet", "Sweet"),
                    ("hot", "hot"),
                    ("pickles", "pickles"),
                    ("other", "other"),
                ],
                max_length=10,
            ),
        ),
    ]
